### ISSUE TITLE
Error: Exception: Invalid syntax for time format

### ISSUE THREAD

**Issue by srvsxc** [peterkuma/cl2nc#1]
Hi,
Having the following error for converting cl51 data.

`Traceback (most recent call last):
  File "/home/sourav/anaconda3/bin/cl2nc", line 240, in read_input
    d.update(line0(line))
  File "/home/sourav/anaconda3/bin/cl2nc", line 51, in line0
    if m is None: raise Exception('Invalid syntax for time format')
Exception: Invalid syntax for time format

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sourav/anaconda3/bin/cl2nc", line 478, in <module>
    'check': args.check
  File "/home/sourav/anaconda3/bin/cl2nc", line 275, in read_input
    raise Exception('Error on line %d: %s: %s' % (line_number, e, line))
Exception: Error on line 4: Invalid syntax for time format: CL010326
`

Any suggestion? 
Thanks in advance

**Comment by peterkuma** [comment]
_[Already resolved in private e-mail communication, but copying the response here for anyone reading github comments.]_

The error is due to cl2nc currently not supporting Python 3 - please use Python 2.7 instead.
